server:
  port: 8888
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/paascloud_mdc?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql

